### PR TITLE
Add PrintWindow activity

### PR DESCRIPTION
**Pull request by billxiao**
Add a new PrintWindow activity to taking screenshot even when screen is locked by using PrintWindow API

### CODE REVIEW

**Comment by skadefro** [comment]
Looks clean, and works for me too. 
I am not sure about the name thou. It feels wrong, but I don't have a better name.
Also, could you please accept the cla ( click details, then click "sign in with github" )

**Comment by billxiao** [comment]
Allan, I've signed the CLA.

**Comment by billxiao** [comment]
image

**Comment by billxiao** [comment]
I've signed the CLA multiple times. But the status is still pending. Why? Is there a bug between CLA and Github?

**Comment by skadefro** [comment]
It must be bugged yes ... But you just confirmed you agree here, so I'm good.

**Comment by skadefro** [comment]
I will try and see if I can get uploaded a version with your addition later today

**Pull request merged**
